# Versioning System For Tesla
# Tesla RELEASE VERSION
TESLA_VERSION_MAJOR = 1.5
TESLA_VERSION_MINOR = 1
# TESLA_VERSION_MAINTENANCE = Stable

#ifdef TESLA_VERSION_MAINTENANCE
#    VERSION := $(TESLA_VERSION_MAJOR).$(TESLA_VERSION_MINOR)-$(TESLA_VERSION_MAINTENANCE)
#else
    VERSION := $(TESLA_VERSION_MAJOR).$(TESLA_VERSION_MINOR)
#endif

TARGET_PRODUCT_SHORT := $(subst tesla_,,$(TESLA_BUILDTYPE))

# Set TESLA_BUILDTYPE
ifdef TESLA_NIGHTLY
    TESLA_BUILDTYPE := NIGHTLY
endif
ifdef TESLA_EXPERIMENTAL
    TESLA_BUILDTYPE := EXPERIMENTAL
endif
#ifdef TESLA_MAINTENANCE
#    TESLA_BUILDTYPE := MAINTENANCE
#endif
# Set Unofficial if no buildtype set (Buildtype should ONLY be set by TESLA Devs!)
ifdef TESLA_BUILDTYPE
else
    TESLA_BUILDTYPE := OFFICIAL
endif

# Set TESLA version
ifdef TESLA_RELEASE
    TESLA_VERSION := Tesla-v$(VERSION)
else
    TESLA_VERSION := Tesla-v$(VERSION)-$(TESLA_BUILD)-$(TESLA_BUILDTYPE)-$(shell date +%Y%m%d)
endif

TESLA_DISPLAY_VERSION := $(VERSION)
TESLA_DISPLAY_BUILDTYPE := $(TESLA_BUILDTYPE)
TESLA_FINGERPRINT := Tesla/$(VERSION)/$(TARGET_PRODUCT_SHORT)/$(shell date +%Y%m%d)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
  ro.tesla.version=$(TESLA_DISPLAY_VERSION) \
  ro.tesla.build.status=$(TESLA_BUILDTYPE) \
  ro.tesla.releasetype=$(TESLA_BUILDTYPE) \
  ro.tesla.fingerprint=$(TESLA_FINGERPRINT)
